### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by altmank** [obarlik/Json.Net#10]
Is it intentional that you've named this project to show up when people are searching for Newtonsoft.Json package?

**Comment by obarlik** [comment]
nope, if you search for newtonsoft you get that package. 
this name is actually not well thought, 
because i was focused to the function, and therefore it's not an intentionally chosen name.

**Comment by veremenko-y** [comment]
I disagree. It hijacks the name of a very popular package. And searching for `Json.N` returns your package first, because `Net` goes before `NET`. It's not the first time that I accidentally install yours.
