### ISSUE TITLE
Case-insensitive property matching

### ISSUE THREAD

**Issue by johnfnz** [obarlik/Json.Net#4]
Would you be open to providing an option for case-insensitive property matching?

**Comment by obarlik** [comment]
Hi, sorry for late reply.
Thanks for using my library.
Why not, I'll think on that.
maybe you can contribute for that feature.

**Comment by obarlik** [comment]
Thanks johnfnz, I'll check that if ok pull then publish. 
Just wanted to ask in advance, if you had run any performance test 
and compare the results with other libraries?
