### ISSUE TITLE
Serialize anonymous object containing an IP-address, an int and an enum

### ISSUE THREAD

**Issue by McTopaz** [obarlik/Json.Net#6]
**Description**
I'm trying to serialize and instance of a class containing a tuple  type:

`class Configuration`
`{`
`public (IPAddress IpAddress, int Port, Protocols Protocol) NetworkSettings { get; private set; } = (IPAddress.Any, 10001, Protocols.Udp);`
`}`

- The _IPAddress_ type is the System.Net.IpAddress.
- The _Protocols_ type is a custom enum: `enum Protocols { Udp, Tcp }`. 

**To Reproduce**
This is the code I have to serialize the instance of the class:

`var configuration = new Configuration();`
`var converter = new JSonConverter<System.Net.IPAddress>`
`(`
`ip => configuration.NetworkSettings.IpAddress.ToString(),`
`s => System.Net.IPAddress.Parse(s)`
`);`
`var json = JsonNet.Serialize(new configuration(), converter);`

***Note:***
- Since the IPAddress type don't have a default construct, I'm suppose to use a converter.
- I have read, from various sources, that the enum types also need something else to make it work. I have no clue what and how.

**Expected behavior**
I expect the variable json to be a string with the valid json content.

**Real behavior**
The `JSonNet.Serialize()` method throws an _ArgumentException_:
_"The number of generic arguments provided doesn't equal of the generic type definition"._

_Stacktrace:_
- at System.RuntimeType.MakeGenericType(Type[] instantiation)
- at Json.Net.JsonSerializer.Serialize(Object obj, SerializationOptions options)
- at Json.Net.JsonSerializer.Serialize(Object obj, SerializationOptions options)
- at Json.Net.JsonNet.Serialize(Object obj, SerializationOptions options)
- at Json.Net.JsonNet.Serialize(Object obj, IJsonConverter[] converters)

**Info**
 - OS: Windows 10 Pro, x64, v1903
 - JSON.NET: V1.0.18, installed as NuGet package.
 - Visual Studio: Community 2019.
 - Application type: WPF, .NET CORE 3.1

What's wrong?

**Comment by obarlik** [comment]
Sorry for late reply @McTopaz , I've been really busy with business stuff. 
Thanks for reporting this problem. If you can help I can gratefully accept your fix in next release.
I'm not sure when I can fix that but I'll try my best.
